export const FETCH_PRODUCT_PAGINATION_PENDING = 'FETCH_PRODUCT_PAGINATION_PENDING';
export const FETCH_PRODUCT_PAGINATION_RESOLVE = 'FETCH_PRODUCT_PAGINATION_RESOLVE';
export const FETCH_PRODUCT_PAGINATION_REJECT = 'FETCH_PRODUCT_PAGINATION_REJECT';
